# Generated by Django 5.0.8 on 2024-08-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
