# Generated by Django 5.0.8 on 2024-08-09 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_callrecord_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(fields=["sid"], name="api_callrec_sid_d40708_idx"),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["user", "created_at"], name="api_callrec_user_id_0c1079_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["user", "status"], name="api_callrec_user_id_212953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "phone_number"], name="api_contact_user_id_b8f4df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "city"], name="api_contact_user_id_86ce24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactlist",
            index=models.Index(
                fields=["user", "name"], name="api_contact_user_id_7112d9_idx"
            ),
        ),
    ]
