# Generated by Django 5.0.8 on 2024-08-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_callrecord_api_callrec_sid_d40708_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callrecord",
            name="sid",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
