# Generated by Django 5.0.8 on 2024-08-12 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_callrecord_sid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("user", "phone_number")},
        ),
    ]
